#!/usr/bin/env zsh
# MIT License
#
# Copyright (c) 2020 Manish Sahani
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# ########################################################################## #
#                                /!\ Important /!\                           #
# The file is used to as aliasing all the commands, this file is an for ease #
# of user and not a core file for tooling, and has a dependency to .extra,   #
# therefore, this should always be loader after .extra (preferably at last)  #
# ########################################################################## #

# Towared root navigations
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# General Shortcuts
alias g=git
alias p=python
alias vi=nvim
alias cz=chezmoi
alias cze="chezmoi edit --apply"
alias czg="/usr/bin/git --git-dir=$HOME/.local/share/chezmoi/.git/ --work-tree=$HOME/.local/share/chezmoi/"

# Directory listing
alias l="ls -lF --color"
alias ll="ls -lAh --group-directories-first --color"
alias la="ls -lAF --color"
alias lsd="ls -lAF --color | grep --color=never '^d'" # List only dirs
alias ls="command ls --color"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# refresh terminal
alias so="source ~/.zshrc"

alias vi="nvim"
alias vim="nvim"
alias vimwiki="nvim ~/vimwiki/index.wiki"
alias vimconfig="chezmoi edit --apply ~/.config/nvim/init.vim"
# alias termconfig="nvim /mnt/c/Users/SamanthaC/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
